# -*- coding: utf-8 -*-
"""automate_Adinda-Putri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ux1c4QpiJW9Xvu96ndEH4C9tajlaFkBG
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import joblib
import os

def preprocess_data(path):
    # 1. Load dataset
    df = pd.read_csv(path)

    # 2. Drop kolom Id
    if "Id" in df.columns:
        df = df.drop(columns=["Id"])

    # 3. Pisah fitur dan target
    X = df.drop("Species", axis=1)
    y = df["Species"]

    # 4. Encode target
    le = LabelEncoder()
    y = le.fit_transform(y)

    # 5. Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # 6. Scaling
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # 7. Simpan hasil preprocessing (opsional tapi bagus)
    os.makedirs("iris_preprocessing", exist_ok=True)
    joblib.dump(scaler, "iris_preprocessing/scaler.pkl")
    joblib.dump(le, "iris_preprocessing/label_encoder.pkl")

    return X_train, X_test, y_train, y_test

if __name__ == "__main__":
    X_train, X_test, y_train, y_test = preprocess_data("Iris.csv")
    print("Preprocessing berhasil")

